# Generated by Django 5.1.6 on 2025-02-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('x', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('ownsite', models.URLField()),
            ],
        ),
    ]
