# Generated by Django 5.1.6 on 2025-02-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='icon',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
