# Generated by Django 5.1.6 on 2025-02-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='x',
        ),
        migrations.AddField(
            model_name='site',
            name='twitter_x',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='instagram',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='ownsite',
            field=models.URLField(default=''),
        ),
    ]
