# Generated by Django 5.1.6 on 2025-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_remove_site_x_site_twitter_x_alter_site_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='ownsite',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='twitter_x',
            field=models.URLField(blank=True),
        ),
    ]
