# Generated by Django 5.1.6 on 2025-02-16 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_site_facebook_alter_site_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='icon',
            new_name='icone',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='site',
            name='ownsite',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('descricao', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
