# Generated by Django 5.1.6 on 2025-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_rename_description_site_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='icone',
            field=models.ImageField(upload_to=''),
        ),
    ]
