# Generated by Django 5.1.6 on 2025-02-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_site_icone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='descricao',
            new_name='name',
        ),
    ]
