# Generated by Django 5.1.6 on 2025-02-17 19:45

import colorfield.fields
import sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_rename_name_link_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='cor_de_fundo',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='site',
            name='cor_de_texto',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='site',
            name='icone',
            field=models.FileField(upload_to='', validators=[sites.models.validate_file_extension], verbose_name='Image'),
        ),
    ]
